" Load vim-plug
source ~/common/nvim/plug.vim

" Load plugin directory
call plug#begin('~/.nvim/user-plugins')

" Load plugins
" see https://github.com/junegunn/vim-plug readme file for examples

" Plugins
Plug 'Valloric/YouCompleteMe'
Plug 'neomake/neomake'
Plug 'sakhnik/nvim-gdb'
Plug 'triglav/vim-visual-increment'
Plug 'rust-lang/rust.vim'
Plug 'preservim/nerdtree'

" Initialize plugin system
call plug#end()

" load vim settings
source ~/common/vim/vimrc

