" Load vim-plug
source ~/dotfiles/nvim/plug.vim

" Load plugin directory
call plug#begin('~/.nvim/user-plugins')

" Load plugins
" see https://github.com/junegunn/vim-plug readme file for examples

" Plugins
Plug 'Valloric/YouCompleteMe'
Plug 'neomake/neomake'
Plug 'sakhnik/nvim-gdb'
Plug 'triglav/vim-visual-increment'

" Initialize plugin system
call plug#end()

" load vim settings
source ~/dotfiles/vim/vimrc

