# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/bowers/.zshrc'

fpath+=~/.zfunc

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Add home bin dir to path
export PATH=$PATH:~/bin:/opt/cross-sh/bin

# Emulate 256 color xterm
export TERM=xterm-256color

# Set editor to nvim
export VISUAL="open_nvim"
export EDITOR="$VISUAL" 
# Set prompt
source ~/common/scripts/powerline-prompt.sh

# Auto suggestions
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# alias commands
alias vim=nvim
alias ls="ls --color=auto"
alias ll="ls -la"
alias l.="ls -d .*"

# python virtualenv
export WORKON_HOME=~/.virtualenvs
source /usr/bin/virtualenvwrapper.sh
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python2.7
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/bin/virtualenv2

# Attach to a tmux session (if there is none, one will be created)
if [ -t 0 ] && [[ -z $TMUX ]]; then; tmux attach || tmux new; fi
